services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
  
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  conduit-backend:
    build:
      context: ./conduit-backend
      dockerfile: Dockerfile
    container_name: conduit-backend
    restart: unless-stopped
    environment:
      DEBUG_VALUE: ${DEBUG_VALUE}
      SECRET_KEY_DB: ${SECRET_KEY_DB}
      ALLOWED_HOSTS_DB: ${ALLOWED_HOSTS_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HOST_DB: db
      PORT_DB: 5432
    depends_on:
      - db
    ports:
      - "${DJANGO_PORT}:8000"

  conduit-frontend:
    build:
      context: ./conduit-frontend
      dockerfile: Dockerfile
    container_name: conduit-frontend
    restart: unless-stopped
    ports:
      - "8282:80"
    

     
volumes:
 postgres_data:

